feat: add lint_filename.go script
pion/.goassets pull request #176
Opened 2023-09-03 09:13 UTC by kehiy

#### Description
rewrite the lint file name script in Golang.

#### Reference issue
Fixes #163

2023-09-04 14:56 UTC, kehiy commented
@Sean-Der can you have a review?

2023-09-06 06:58 UTC, stv0g requested changes
Looks good to me :) We now only need to invoke the new Go script instead of the shell script here:

https://github.com/pion/.goassets/blob/965ecf8cc04ca3535ee99556c40b3cc27af671d2/.github/workflows/lint.reusable.yml#L35

2023-09-06 06:58 UTC, stv0g commented on scripts/lint_filename.go
> +*/
```suggestion
// SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
// SPDX-License-Identifier: MIT
```

2023-09-06 06:58 UTC, stv0g commented on scripts/lint_filename.go
> +	err := filepath.Walk(parentDir, func(path string, info os.FileInfo, err error) error {
```suggestion
	if err := filepath.Walk(parentDir, func(path string, info os.FileInfo, err error) error {
```

2023-09-06 06:58 UTC, stv0g commented on scripts/lint_filename.go
> +	if err != nil {
```suggestion
	}); err != nil {
```

I usually prefer this shorter form. But its a personal preference. Feel free to accept or decline this suggestion how you like :)

2023-09-08 07:54 UTC, kehiy commented
@stv0g is that okay now?

2023-09-08 09:11 UTC, stv0g commented
@kehiy It seems like you have resolved my previous review comments without addressing them?

Please also not that the CI is currently failing. We can only merge it once all the checks are passing.

Thanks for your support :)

2023-09-08 09:11 UTC, stv0g commented on .github/workflows/lint.reusable.yml
> +        run: .github/.goassets/scripts/lint-filename.go
I assume we need to use a `go run .github/.goassets/scripts/lint-filename.go` here.
```suggestion
        run: go run .github/.goassets/scripts/lint-filename.go
```

2023-09-08 09:21 UTC, kehiy commented
@stv0g what so you mean `addressing them`?
about ci I tried to fix them but its true we can merge it

2023-09-08 09:23 UTC, stv0g commented
> @stv0g what so you mean addressing them?

I've proposed changes which you have ignored and marked the corresponding threads as resolved.
I have now went ahead an unresolved them. Please commit the suggested changes.

2023-09-08 09:25 UTC, kehiy commented
> > @stv0g what so you mean addressing them?
> 
> I've proposed changes which you have ignored and marked the corresponding threads as resolved. I have now went ahead an unresolved them. Please commit the suggested changes.

oh, yeas I can see, but I committed the suggestions on GitHub directly!
I will try to do it againg.

2023-09-08 09:29 UTC, kehiy commented
@stv0g I think its ok now
Is that?

2023-09-08 09:46 UTC, stv0g commented
Okay cool :) It looks alright now 👍🏻 

You would only need to fix the CI pipeline. Here are some tips:

1. Add the same SPDX headers to the `go.mod` mod file in the beginning
2. Add your name + email (`Kay <kehiiiiya@gmail.com>`) to the `AUTHORS.txt` file. Make sure the entry is at the correct place (alphabetically ordered)
3. [Squash all your commits](https://www.baeldung.com/ops/git-squash-commits) and give it a correct commit message.

2023-09-09 10:32 UTC, kehiy commented
@stv0g Everything is fixed just for `squashing` the commits I got a lot of errors and conflicts, and I think it's better to squash them when you want to merge them on GitHub.

2023-09-09 10:46 UTC, stv0g commented
Hi, you can also squash lically. I added a link about it in my previous comment

2023-09-09 10:51 UTC, kehiy commented
okay, I tried to do this locally, but I will try again.

2023-09-09 11:04 UTC, kehiy commented
@stv0g can you have a review?

2023-09-10 18:28 UTC, Sean-Der approved these changes

2023-09-10 18:28 UTC, merged