Add lint go mod golang script
pion/.goassets pull request #182
Opened 2023-09-17 09:56 UTC by kehiy

#### Description

#### Reference issue
Related #163

2023-09-18 07:13 UTC, stv0g requested changes
I think we should be able to run those scripts independently and not just via a single main function. Lets keep a single file and main() functionality per script.

2023-09-18 08:29 UTC, kehiy commented
@stv0g I tried to do this, but I got errors because go.mod file (just one main function we can have per main package)

2023-09-18 09:19 UTC, stv0g commented
I see. But running a single script should not require a Go module. Can you try it without go.mod?

2023-09-18 09:23 UTC, kehiy commented
yes, I will try to run them without `go.mod`.

2023-09-19 14:15 UTC, Sean-Der commented
@kehiy are you explicitly calling `go run lint_go_mod_version.go`?

You can have two files with a main in the same directory.

```
duboisea@b0f1d8547841:~/foo$ cat a.go
package main

import "fmt"

func main() {
	fmt.Println("a")
}
duboisea@b0f1d8547841:~/foo$ go run a.go
a
duboisea@b0f1d8547841:~/foo$ cat b.go
package main

import "fmt"

func main() {
	fmt.Println("b")
}
duboisea@b0f1d8547841:~/foo$ go run b.go
b
```

2023-09-19 14:18 UTC, kehiy commented
@Sean-Der 
the error is from IDE!

when I try to run them
just version linter raises errors
I will push my changes then you can see

2023-09-20 19:35 UTC, kehiy commented
@Sean-Der @stv0g can you have a review?

2023-09-20 19:43 UTC, Sean-Der commented
Yes! I will get this merged today, thanks for working on it :)

2023-09-20 20:21 UTC, kehiy commented
@Sean-Der thankssss

2023-09-25 11:49 UTC, stv0g requested changes
Just minor nit-picks. But overall it looks good :)

I will let it up to you if you use the `modfile` package for parsing the `go.mod` file or whether you keep the Regex.

2023-09-25 11:49 UTC, stv0g commented on scripts/lint_go_mod_version.go
> +func readCiConf(ciConfPath string) error {
```suggestion
func readCIConf(ciConfPath string) error {
```

In Go, acronyms are usually capitalized.

2023-09-25 11:49 UTC, stv0g commented on scripts/lint_go_mod_version.go
It would even nicer if we would use the [`modfile` package](https://pkg.go.dev/golang.org/x/mod/modfile). This would allow us to us the same code which Go uses itself to parse the file.

2023-09-25 11:53 UTC, kehiy commented on scripts/lint_go_mod_version.go
How can I do this?
I can't get it

2023-09-25 12:00 UTC, stv0g commented on scripts/lint_go_mod_version.go
You would use the new package by running:

```shell
go get golang.org/x/mod/modfile
```

Then you can use the new package to load and parse the `go.mod` file:

```go
import (
    "os"
    "fmt"
    "golang.org/x/mod/modfile"
)

[...]

goModFile := "go.mod"

goModContents, err := os.ReadFile(goModFile)
if err != nil { ... }

goMod, err := modfile.Parse(goModFile, goModContents, nil)
if err != nil { ... }

fmt.Printf("This is the version: %s", goMod.Go.Version)
```

2023-09-25 12:02 UTC, stv0g commented
Did you check that the function name you changed in 546028e0ff1fdc4cf8262ad85d569bf31c0e9820 is also changed at the call site?

2023-09-25 12:10 UTC, kehiy commented on scripts/lint_go_mod_version.go
can I fix this in another PR?

2023-09-25 12:11 UTC, kehiy commented
@stv0g the function name is okay now.

2023-10-06 13:49 UTC, kehiy commented
guys, can we merge this?
or is there any change?

2023-10-21 14:23 UTC, kehiy commented
@Sean-Der @stv0g guys can you have a review? if you need I can use gomod package also and push it.

2023-11-03 20:40 UTC, closed without merging